// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kv.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Internal representations for operations.
type Op int32

const (
	Op_GET   Op = 0
	Op_SET   Op = 1
	Op_CLEAR Op = 2
	Op_CAS   Op = 3
)

var Op_name = map[int32]string{
	0: "GET",
	1: "SET",
	2: "CLEAR",
	3: "CAS",
}

var Op_value = map[string]int32{
	"GET":   0,
	"SET":   1,
	"CLEAR": 2,
	"CAS":   3,
}

func (x Op) String() string {
	return proto.EnumName(Op_name, int32(x))
}

func (Op) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{0}
}

// Represents a single key, used for gets.
type Key struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{0}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// Represents a single value, can be used for put etc.
type Value struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{1}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Represent a key-value pair that is used to return results.
type KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{2}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Represent a void message indicating success
type Success struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Success) Reset()         { *m = Success{} }
func (m *Success) String() string { return proto.CompactTextString(m) }
func (*Success) ProtoMessage()    {}
func (*Success) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{3}
}

func (m *Success) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Success.Unmarshal(m, b)
}
func (m *Success) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Success.Marshal(b, m, deterministic)
}
func (m *Success) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Success.Merge(m, src)
}
func (m *Success) XXX_Size() int {
	return xxx_messageInfo_Success.Size(m)
}
func (m *Success) XXX_DiscardUnknown() {
	xxx_messageInfo_Success.DiscardUnknown(m)
}

var xxx_messageInfo_Success proto.InternalMessageInfo

// Represents an error.
type Error struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{4}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// Represents an argument for CAS
type CASArg struct {
	Kv                   *KeyValue `protobuf:"bytes,1,opt,name=kv,proto3" json:"kv,omitempty"`
	Value                *Value    `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CASArg) Reset()         { *m = CASArg{} }
func (m *CASArg) String() string { return proto.CompactTextString(m) }
func (*CASArg) ProtoMessage()    {}
func (*CASArg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{5}
}

func (m *CASArg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CASArg.Unmarshal(m, b)
}
func (m *CASArg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CASArg.Marshal(b, m, deterministic)
}
func (m *CASArg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CASArg.Merge(m, src)
}
func (m *CASArg) XXX_Size() int {
	return xxx_messageInfo_CASArg.Size(m)
}
func (m *CASArg) XXX_DiscardUnknown() {
	xxx_messageInfo_CASArg.DiscardUnknown(m)
}

var xxx_messageInfo_CASArg proto.InternalMessageInfo

func (m *CASArg) GetKv() *KeyValue {
	if m != nil {
		return m.Kv
	}
	return nil
}

func (m *CASArg) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

// Represents an empty message
type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{6}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// Represents a case where we need the client to connect
// to another server.
type Redirect struct {
	Server               string   `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Redirect) Reset()         { *m = Redirect{} }
func (m *Redirect) String() string { return proto.CompactTextString(m) }
func (*Redirect) ProtoMessage()    {}
func (*Redirect) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{7}
}

func (m *Redirect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Redirect.Unmarshal(m, b)
}
func (m *Redirect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Redirect.Marshal(b, m, deterministic)
}
func (m *Redirect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Redirect.Merge(m, src)
}
func (m *Redirect) XXX_Size() int {
	return xxx_messageInfo_Redirect.Size(m)
}
func (m *Redirect) XXX_DiscardUnknown() {
	xxx_messageInfo_Redirect.DiscardUnknown(m)
}

var xxx_messageInfo_Redirect proto.InternalMessageInfo

func (m *Redirect) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

// Represents an operation result.
type Result struct {
	// Types that are valid to be assigned to Result:
	//	*Result_Redirect
	//	*Result_Kv
	//	*Result_S
	Result               isResult_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{8}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

type isResult_Result interface {
	isResult_Result()
}

type Result_Redirect struct {
	Redirect *Redirect `protobuf:"bytes,1,opt,name=redirect,proto3,oneof"`
}

type Result_Kv struct {
	Kv *KeyValue `protobuf:"bytes,2,opt,name=kv,proto3,oneof"`
}

type Result_S struct {
	S *Success `protobuf:"bytes,3,opt,name=s,proto3,oneof"`
}

func (*Result_Redirect) isResult_Result() {}

func (*Result_Kv) isResult_Result() {}

func (*Result_S) isResult_Result() {}

func (m *Result) GetResult() isResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Result) GetRedirect() *Redirect {
	if x, ok := m.GetResult().(*Result_Redirect); ok {
		return x.Redirect
	}
	return nil
}

func (m *Result) GetKv() *KeyValue {
	if x, ok := m.GetResult().(*Result_Kv); ok {
		return x.Kv
	}
	return nil
}

func (m *Result) GetS() *Success {
	if x, ok := m.GetResult().(*Result_S); ok {
		return x.S
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Result) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Result_Redirect)(nil),
		(*Result_Kv)(nil),
		(*Result_S)(nil),
	}
}

// A type for arguments across all operations
type Command struct {
	Operation Op `protobuf:"varint,1,opt,name=operation,proto3,enum=pb.Op" json:"operation,omitempty"`
	// Types that are valid to be assigned to Arg:
	//	*Command_Get
	//	*Command_Set
	//	*Command_Clear
	//	*Command_Cas
	Arg                  isCommand_Arg `protobuf_oneof:"arg"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{9}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetOperation() Op {
	if m != nil {
		return m.Operation
	}
	return Op_GET
}

type isCommand_Arg interface {
	isCommand_Arg()
}

type Command_Get struct {
	Get *Key `protobuf:"bytes,2,opt,name=get,proto3,oneof"`
}

type Command_Set struct {
	Set *KeyValue `protobuf:"bytes,3,opt,name=set,proto3,oneof"`
}

type Command_Clear struct {
	Clear *Empty `protobuf:"bytes,4,opt,name=clear,proto3,oneof"`
}

type Command_Cas struct {
	Cas *CASArg `protobuf:"bytes,5,opt,name=cas,proto3,oneof"`
}

func (*Command_Get) isCommand_Arg() {}

func (*Command_Set) isCommand_Arg() {}

func (*Command_Clear) isCommand_Arg() {}

func (*Command_Cas) isCommand_Arg() {}

func (m *Command) GetArg() isCommand_Arg {
	if m != nil {
		return m.Arg
	}
	return nil
}

func (m *Command) GetGet() *Key {
	if x, ok := m.GetArg().(*Command_Get); ok {
		return x.Get
	}
	return nil
}

func (m *Command) GetSet() *KeyValue {
	if x, ok := m.GetArg().(*Command_Set); ok {
		return x.Set
	}
	return nil
}

func (m *Command) GetClear() *Empty {
	if x, ok := m.GetArg().(*Command_Clear); ok {
		return x.Clear
	}
	return nil
}

func (m *Command) GetCas() *CASArg {
	if x, ok := m.GetArg().(*Command_Cas); ok {
		return x.Cas
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Command) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Command_Get)(nil),
		(*Command_Set)(nil),
		(*Command_Clear)(nil),
		(*Command_Cas)(nil),
	}
}

// A log entry
type Entry struct {
	Term                 int64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Index                int64    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Cmd                  *Command `protobuf:"bytes,3,opt,name=cmd,proto3" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{10}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Entry) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Entry) GetCmd() *Command {
	if m != nil {
		return m.Cmd
	}
	return nil
}

// Input to AppendEntries (as defined in Figure 2)
type AppendEntriesArgs struct {
	Term                 int64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderID             string   `protobuf:"bytes,2,opt,name=leaderID,proto3" json:"leaderID,omitempty"`
	PrevLogIndex         int64    `protobuf:"varint,3,opt,name=prevLogIndex,proto3" json:"prevLogIndex,omitempty"`
	PrevLogTerm          int64    `protobuf:"varint,4,opt,name=prevLogTerm,proto3" json:"prevLogTerm,omitempty"`
	LeaderCommit         int64    `protobuf:"varint,5,opt,name=leaderCommit,proto3" json:"leaderCommit,omitempty"`
	Entries              []*Entry `protobuf:"bytes,6,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesArgs) Reset()         { *m = AppendEntriesArgs{} }
func (m *AppendEntriesArgs) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesArgs) ProtoMessage()    {}
func (*AppendEntriesArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{11}
}

func (m *AppendEntriesArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesArgs.Unmarshal(m, b)
}
func (m *AppendEntriesArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesArgs.Marshal(b, m, deterministic)
}
func (m *AppendEntriesArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesArgs.Merge(m, src)
}
func (m *AppendEntriesArgs) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesArgs.Size(m)
}
func (m *AppendEntriesArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesArgs.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesArgs proto.InternalMessageInfo

func (m *AppendEntriesArgs) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesArgs) GetLeaderID() string {
	if m != nil {
		return m.LeaderID
	}
	return ""
}

func (m *AppendEntriesArgs) GetPrevLogIndex() int64 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntriesArgs) GetPrevLogTerm() int64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntriesArgs) GetLeaderCommit() int64 {
	if m != nil {
		return m.LeaderCommit
	}
	return 0
}

func (m *AppendEntriesArgs) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

// Output from AppendEntries
type AppendEntriesRet struct {
	Term                 int64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesRet) Reset()         { *m = AppendEntriesRet{} }
func (m *AppendEntriesRet) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesRet) ProtoMessage()    {}
func (*AppendEntriesRet) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{12}
}

func (m *AppendEntriesRet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesRet.Unmarshal(m, b)
}
func (m *AppendEntriesRet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesRet.Marshal(b, m, deterministic)
}
func (m *AppendEntriesRet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesRet.Merge(m, src)
}
func (m *AppendEntriesRet) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesRet.Size(m)
}
func (m *AppendEntriesRet) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesRet.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesRet proto.InternalMessageInfo

func (m *AppendEntriesRet) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesRet) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// Input to RequestVote
type RequestVoteArgs struct {
	Term                 int64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateID          string   `protobuf:"bytes,2,opt,name=candidateID,proto3" json:"candidateID,omitempty"`
	LastLogIndex         int64    `protobuf:"varint,3,opt,name=lastLogIndex,proto3" json:"lastLogIndex,omitempty"`
	LasLogTerm           int64    `protobuf:"varint,4,opt,name=lasLogTerm,proto3" json:"lasLogTerm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteArgs) Reset()         { *m = RequestVoteArgs{} }
func (m *RequestVoteArgs) String() string { return proto.CompactTextString(m) }
func (*RequestVoteArgs) ProtoMessage()    {}
func (*RequestVoteArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{13}
}

func (m *RequestVoteArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteArgs.Unmarshal(m, b)
}
func (m *RequestVoteArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteArgs.Marshal(b, m, deterministic)
}
func (m *RequestVoteArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteArgs.Merge(m, src)
}
func (m *RequestVoteArgs) XXX_Size() int {
	return xxx_messageInfo_RequestVoteArgs.Size(m)
}
func (m *RequestVoteArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteArgs.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteArgs proto.InternalMessageInfo

func (m *RequestVoteArgs) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteArgs) GetCandidateID() string {
	if m != nil {
		return m.CandidateID
	}
	return ""
}

func (m *RequestVoteArgs) GetLastLogIndex() int64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *RequestVoteArgs) GetLasLogTerm() int64 {
	if m != nil {
		return m.LasLogTerm
	}
	return 0
}

// Output from RequestVote
type RequestVoteRet struct {
	Term                 int64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted          bool     `protobuf:"varint,2,opt,name=voteGranted,proto3" json:"voteGranted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteRet) Reset()         { *m = RequestVoteRet{} }
func (m *RequestVoteRet) String() string { return proto.CompactTextString(m) }
func (*RequestVoteRet) ProtoMessage()    {}
func (*RequestVoteRet) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{14}
}

func (m *RequestVoteRet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteRet.Unmarshal(m, b)
}
func (m *RequestVoteRet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteRet.Marshal(b, m, deterministic)
}
func (m *RequestVoteRet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteRet.Merge(m, src)
}
func (m *RequestVoteRet) XXX_Size() int {
	return xxx_messageInfo_RequestVoteRet.Size(m)
}
func (m *RequestVoteRet) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteRet.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteRet proto.InternalMessageInfo

func (m *RequestVoteRet) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteRet) GetVoteGranted() bool {
	if m != nil {
		return m.VoteGranted
	}
	return false
}

// Request from client
type ClientRequest struct {
	Operation            string   `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClientID             string   `protobuf:"bytes,3,opt,name=clientID,proto3" json:"clientID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientRequest) Reset()         { *m = ClientRequest{} }
func (m *ClientRequest) String() string { return proto.CompactTextString(m) }
func (*ClientRequest) ProtoMessage()    {}
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{15}
}

func (m *ClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientRequest.Unmarshal(m, b)
}
func (m *ClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientRequest.Marshal(b, m, deterministic)
}
func (m *ClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientRequest.Merge(m, src)
}
func (m *ClientRequest) XXX_Size() int {
	return xxx_messageInfo_ClientRequest.Size(m)
}
func (m *ClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientRequest proto.InternalMessageInfo

func (m *ClientRequest) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *ClientRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ClientRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

// Response to client
type ClientResponse struct {
	ViewId               int64    `protobuf:"varint,1,opt,name=viewId,proto3" json:"viewId,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClientID             string   `protobuf:"bytes,3,opt,name=clientID,proto3" json:"clientID,omitempty"`
	Node                 string   `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
	NodeResult           *Result  `protobuf:"bytes,5,opt,name=nodeResult,proto3" json:"nodeResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientResponse) Reset()         { *m = ClientResponse{} }
func (m *ClientResponse) String() string { return proto.CompactTextString(m) }
func (*ClientResponse) ProtoMessage()    {}
func (*ClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{16}
}

func (m *ClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientResponse.Unmarshal(m, b)
}
func (m *ClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientResponse.Marshal(b, m, deterministic)
}
func (m *ClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientResponse.Merge(m, src)
}
func (m *ClientResponse) XXX_Size() int {
	return xxx_messageInfo_ClientResponse.Size(m)
}
func (m *ClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientResponse proto.InternalMessageInfo

func (m *ClientResponse) GetViewId() int64 {
	if m != nil {
		return m.ViewId
	}
	return 0
}

func (m *ClientResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ClientResponse) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *ClientResponse) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *ClientResponse) GetNodeResult() *Result {
	if m != nil {
		return m.NodeResult
	}
	return nil
}

type PrePrepareMsg struct {
	ViewId               int64          `protobuf:"varint,1,opt,name=viewId,proto3" json:"viewId,omitempty"`
	SequenceID           int64          `protobuf:"varint,2,opt,name=sequenceID,proto3" json:"sequenceID,omitempty"`
	Digest               string         `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Request              *ClientRequest `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	Node                 string         `protobuf:"bytes,5,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PrePrepareMsg) Reset()         { *m = PrePrepareMsg{} }
func (m *PrePrepareMsg) String() string { return proto.CompactTextString(m) }
func (*PrePrepareMsg) ProtoMessage()    {}
func (*PrePrepareMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{17}
}

func (m *PrePrepareMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrePrepareMsg.Unmarshal(m, b)
}
func (m *PrePrepareMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrePrepareMsg.Marshal(b, m, deterministic)
}
func (m *PrePrepareMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrePrepareMsg.Merge(m, src)
}
func (m *PrePrepareMsg) XXX_Size() int {
	return xxx_messageInfo_PrePrepareMsg.Size(m)
}
func (m *PrePrepareMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PrePrepareMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PrePrepareMsg proto.InternalMessageInfo

func (m *PrePrepareMsg) GetViewId() int64 {
	if m != nil {
		return m.ViewId
	}
	return 0
}

func (m *PrePrepareMsg) GetSequenceID() int64 {
	if m != nil {
		return m.SequenceID
	}
	return 0
}

func (m *PrePrepareMsg) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *PrePrepareMsg) GetRequest() *ClientRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *PrePrepareMsg) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

type PrepareMsg struct {
	ViewId               int64    `protobuf:"varint,1,opt,name=viewId,proto3" json:"viewId,omitempty"`
	SequenceID           int64    `protobuf:"varint,2,opt,name=sequenceID,proto3" json:"sequenceID,omitempty"`
	Digest               string   `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Node                 string   `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareMsg) Reset()         { *m = PrepareMsg{} }
func (m *PrepareMsg) String() string { return proto.CompactTextString(m) }
func (*PrepareMsg) ProtoMessage()    {}
func (*PrepareMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{18}
}

func (m *PrepareMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareMsg.Unmarshal(m, b)
}
func (m *PrepareMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareMsg.Marshal(b, m, deterministic)
}
func (m *PrepareMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareMsg.Merge(m, src)
}
func (m *PrepareMsg) XXX_Size() int {
	return xxx_messageInfo_PrepareMsg.Size(m)
}
func (m *PrepareMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareMsg proto.InternalMessageInfo

func (m *PrepareMsg) GetViewId() int64 {
	if m != nil {
		return m.ViewId
	}
	return 0
}

func (m *PrepareMsg) GetSequenceID() int64 {
	if m != nil {
		return m.SequenceID
	}
	return 0
}

func (m *PrepareMsg) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *PrepareMsg) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

type CommitMsg struct {
	ViewId               int64    `protobuf:"varint,1,opt,name=viewId,proto3" json:"viewId,omitempty"`
	SequenceID           int64    `protobuf:"varint,2,opt,name=sequenceID,proto3" json:"sequenceID,omitempty"`
	Digest               string   `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Node                 string   `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitMsg) Reset()         { *m = CommitMsg{} }
func (m *CommitMsg) String() string { return proto.CompactTextString(m) }
func (*CommitMsg) ProtoMessage()    {}
func (*CommitMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{19}
}

func (m *CommitMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitMsg.Unmarshal(m, b)
}
func (m *CommitMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitMsg.Marshal(b, m, deterministic)
}
func (m *CommitMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitMsg.Merge(m, src)
}
func (m *CommitMsg) XXX_Size() int {
	return xxx_messageInfo_CommitMsg.Size(m)
}
func (m *CommitMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CommitMsg proto.InternalMessageInfo

func (m *CommitMsg) GetViewId() int64 {
	if m != nil {
		return m.ViewId
	}
	return 0
}

func (m *CommitMsg) GetSequenceID() int64 {
	if m != nil {
		return m.SequenceID
	}
	return 0
}

func (m *CommitMsg) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *CommitMsg) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

type LogEntry struct {
	// Types that are valid to be assigned to Entry:
	//	*LogEntry_Preprep
	//	*LogEntry_Prep
	//	*LogEntry_Commit
	Entry                isLogEntry_Entry `protobuf_oneof:"entry"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}
func (*LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{20}
}

func (m *LogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEntry.Unmarshal(m, b)
}
func (m *LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEntry.Marshal(b, m, deterministic)
}
func (m *LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntry.Merge(m, src)
}
func (m *LogEntry) XXX_Size() int {
	return xxx_messageInfo_LogEntry.Size(m)
}
func (m *LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntry proto.InternalMessageInfo

type isLogEntry_Entry interface {
	isLogEntry_Entry()
}

type LogEntry_Preprep struct {
	Preprep *PrePrepareMsg `protobuf:"bytes,1,opt,name=preprep,proto3,oneof"`
}

type LogEntry_Prep struct {
	Prep *PrepareMsg `protobuf:"bytes,2,opt,name=prep,proto3,oneof"`
}

type LogEntry_Commit struct {
	Commit *CommitMsg `protobuf:"bytes,3,opt,name=commit,proto3,oneof"`
}

func (*LogEntry_Preprep) isLogEntry_Entry() {}

func (*LogEntry_Prep) isLogEntry_Entry() {}

func (*LogEntry_Commit) isLogEntry_Entry() {}

func (m *LogEntry) GetEntry() isLogEntry_Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (m *LogEntry) GetPreprep() *PrePrepareMsg {
	if x, ok := m.GetEntry().(*LogEntry_Preprep); ok {
		return x.Preprep
	}
	return nil
}

func (m *LogEntry) GetPrep() *PrepareMsg {
	if x, ok := m.GetEntry().(*LogEntry_Prep); ok {
		return x.Prep
	}
	return nil
}

func (m *LogEntry) GetCommit() *CommitMsg {
	if x, ok := m.GetEntry().(*LogEntry_Commit); ok {
		return x.Commit
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LogEntry) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LogEntry_Preprep)(nil),
		(*LogEntry_Prep)(nil),
		(*LogEntry_Commit)(nil),
	}
}

type PbftMsgAccepted struct {
	ViewId               int64    `protobuf:"varint,1,opt,name=viewId,proto3" json:"viewId,omitempty"`
	SequenceID           int64    `protobuf:"varint,2,opt,name=sequenceID,proto3" json:"sequenceID,omitempty"`
	Success              bool     `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	TypeOfAccepted       string   `protobuf:"bytes,4,opt,name=typeOfAccepted,proto3" json:"typeOfAccepted,omitempty"`
	Node                 string   `protobuf:"bytes,5,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PbftMsgAccepted) Reset()         { *m = PbftMsgAccepted{} }
func (m *PbftMsgAccepted) String() string { return proto.CompactTextString(m) }
func (*PbftMsgAccepted) ProtoMessage()    {}
func (*PbftMsgAccepted) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{21}
}

func (m *PbftMsgAccepted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbftMsgAccepted.Unmarshal(m, b)
}
func (m *PbftMsgAccepted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbftMsgAccepted.Marshal(b, m, deterministic)
}
func (m *PbftMsgAccepted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbftMsgAccepted.Merge(m, src)
}
func (m *PbftMsgAccepted) XXX_Size() int {
	return xxx_messageInfo_PbftMsgAccepted.Size(m)
}
func (m *PbftMsgAccepted) XXX_DiscardUnknown() {
	xxx_messageInfo_PbftMsgAccepted.DiscardUnknown(m)
}

var xxx_messageInfo_PbftMsgAccepted proto.InternalMessageInfo

func (m *PbftMsgAccepted) GetViewId() int64 {
	if m != nil {
		return m.ViewId
	}
	return 0
}

func (m *PbftMsgAccepted) GetSequenceID() int64 {
	if m != nil {
		return m.SequenceID
	}
	return 0
}

func (m *PbftMsgAccepted) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PbftMsgAccepted) GetTypeOfAccepted() string {
	if m != nil {
		return m.TypeOfAccepted
	}
	return ""
}

func (m *PbftMsgAccepted) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.Op", Op_name, Op_value)
	proto.RegisterType((*Key)(nil), "pb.Key")
	proto.RegisterType((*Value)(nil), "pb.Value")
	proto.RegisterType((*KeyValue)(nil), "pb.KeyValue")
	proto.RegisterType((*Success)(nil), "pb.Success")
	proto.RegisterType((*Error)(nil), "pb.Error")
	proto.RegisterType((*CASArg)(nil), "pb.CASArg")
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*Redirect)(nil), "pb.Redirect")
	proto.RegisterType((*Result)(nil), "pb.Result")
	proto.RegisterType((*Command)(nil), "pb.Command")
	proto.RegisterType((*Entry)(nil), "pb.Entry")
	proto.RegisterType((*AppendEntriesArgs)(nil), "pb.AppendEntriesArgs")
	proto.RegisterType((*AppendEntriesRet)(nil), "pb.AppendEntriesRet")
	proto.RegisterType((*RequestVoteArgs)(nil), "pb.RequestVoteArgs")
	proto.RegisterType((*RequestVoteRet)(nil), "pb.RequestVoteRet")
	proto.RegisterType((*ClientRequest)(nil), "pb.ClientRequest")
	proto.RegisterType((*ClientResponse)(nil), "pb.ClientResponse")
	proto.RegisterType((*PrePrepareMsg)(nil), "pb.PrePrepareMsg")
	proto.RegisterType((*PrepareMsg)(nil), "pb.PrepareMsg")
	proto.RegisterType((*CommitMsg)(nil), "pb.CommitMsg")
	proto.RegisterType((*LogEntry)(nil), "pb.LogEntry")
	proto.RegisterType((*PbftMsgAccepted)(nil), "pb.PbftMsgAccepted")
}

func init() { proto.RegisterFile("kv.proto", fileDescriptor_2216fe83c9c12408) }

var fileDescriptor_2216fe83c9c12408 = []byte{
	// 1086 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdd, 0x6e, 0xe3, 0xc4,
	0x17, 0xb7, 0xe3, 0x38, 0x4e, 0x4e, 0xb6, 0xd9, 0x74, 0xfe, 0xfb, 0x87, 0xd0, 0xed, 0x76, 0xb3,
	0xb3, 0x2b, 0x40, 0x45, 0x54, 0x55, 0xe0, 0x02, 0x21, 0x84, 0x48, 0xb3, 0xd9, 0xa6, 0x6a, 0x51,
	0xab, 0x49, 0xb5, 0xf7, 0xae, 0x7d, 0x6a, 0x45, 0x4d, 0x6c, 0x33, 0x33, 0x0d, 0x44, 0xdc, 0x70,
	0x8f, 0xb8, 0xe0, 0x92, 0x2b, 0x10, 0x4f, 0xc1, 0x73, 0xf0, 0x18, 0x3c, 0x05, 0x9a, 0xf1, 0x38,
	0xb1, 0xd3, 0x86, 0x95, 0x56, 0x02, 0xa9, 0x52, 0x67, 0xce, 0xc7, 0x9c, 0xdf, 0xf9, 0xf9, 0x7c,
	0x04, 0xea, 0x37, 0xf3, 0x83, 0x94, 0x27, 0x32, 0x21, 0x95, 0xf4, 0x8a, 0xbe, 0x0b, 0xce, 0x29,
	0x2e, 0x48, 0x1b, 0x9c, 0x1b, 0x5c, 0x74, 0xec, 0xae, 0xfd, 0x61, 0x83, 0xa9, 0x23, 0x7d, 0x02,
	0xee, 0x6b, 0x7f, 0x7a, 0x8b, 0xe4, 0x11, 0xb8, 0x73, 0x75, 0x30, 0xca, 0xec, 0x42, 0x7b, 0x50,
	0x3f, 0xc5, 0x45, 0x66, 0x71, 0xc7, 0x79, 0xe5, 0x53, 0x29, 0xfa, 0x34, 0xc0, 0x1b, 0xdf, 0x06,
	0x01, 0x0a, 0x41, 0xdf, 0x03, 0x77, 0xc8, 0x79, 0xc2, 0x95, 0xef, 0x4c, 0x44, 0xb9, 0xef, 0x4c,
	0x44, 0xf4, 0x18, 0x6a, 0x83, 0xfe, 0xb8, 0xcf, 0x23, 0xb2, 0x0b, 0x95, 0x9b, 0xb9, 0x56, 0x35,
	0x7b, 0x0f, 0x0e, 0xd2, 0xab, 0x83, 0x3c, 0x22, 0xab, 0xdc, 0xcc, 0xc9, 0xd3, 0x62, 0x8c, 0x66,
	0xaf, 0xa1, 0x0c, 0x32, 0xad, 0x09, 0xe7, 0x81, 0x3b, 0x9c, 0xa5, 0x72, 0x41, 0x29, 0xd4, 0x19,
	0x86, 0x13, 0x8e, 0x81, 0x24, 0xef, 0x40, 0x4d, 0x20, 0x9f, 0x23, 0x37, 0x21, 0xcd, 0x8d, 0x7e,
	0x0f, 0x35, 0x86, 0xe2, 0x76, 0x2a, 0xc9, 0x3e, 0xd4, 0xb9, 0xb1, 0x2e, 0xc6, 0xce, 0x5f, 0x18,
	0x59, 0x6c, 0xa9, 0x27, 0x7b, 0x1a, 0x61, 0xe5, 0x2e, 0xc2, 0x91, 0xa5, 0x31, 0x3e, 0x06, 0x5b,
	0x74, 0x1c, 0xad, 0x6e, 0x2a, 0xb5, 0x49, 0x7f, 0x64, 0x31, 0x5b, 0x1c, 0xd5, 0xa1, 0xc6, 0x75,
	0x48, 0xfa, 0x87, 0x0d, 0xde, 0x20, 0x99, 0xcd, 0xfc, 0x38, 0x24, 0x2f, 0xa0, 0x91, 0xa4, 0xc8,
	0x7d, 0x39, 0x49, 0x62, 0x1d, 0xbf, 0xd5, 0xab, 0x29, 0xd7, 0xf3, 0x94, 0xad, 0x14, 0xe4, 0x31,
	0x38, 0x11, 0x4a, 0x13, 0xd9, 0x33, 0x91, 0x47, 0x16, 0x53, 0x52, 0xd2, 0x05, 0x47, 0xa0, 0x34,
	0x71, 0xd7, 0x61, 0x29, 0x15, 0x79, 0x06, 0x6e, 0x30, 0x45, 0x9f, 0x77, 0xaa, 0x2b, 0xee, 0x34,
	0x57, 0x23, 0x8b, 0x65, 0x1a, 0xb2, 0x07, 0x4e, 0xe0, 0x8b, 0x8e, 0xab, 0x0d, 0x40, 0x19, 0x64,
	0x5f, 0x45, 0x3d, 0x11, 0xf8, 0xe2, 0xc8, 0x05, 0xc7, 0xe7, 0x11, 0xbd, 0x00, 0x77, 0x18, 0x4b,
	0xbe, 0x20, 0x04, 0xaa, 0x12, 0xf9, 0x4c, 0x43, 0x76, 0x98, 0x3e, 0xab, 0x32, 0x98, 0xc4, 0x21,
	0x7e, 0xa7, 0x71, 0x3a, 0x2c, 0xbb, 0x90, 0x27, 0xe0, 0x04, 0xb3, 0xb0, 0x48, 0x8b, 0xc9, 0x9d,
	0x29, 0x39, 0xfd, 0xd3, 0x86, 0xed, 0x7e, 0x9a, 0x62, 0x1c, 0xaa, 0x87, 0x27, 0x28, 0xfa, 0x3c,
	0x12, 0xf7, 0x3e, 0xbf, 0x03, 0xf5, 0x29, 0xfa, 0x21, 0xf2, 0x93, 0x97, 0xa6, 0xd0, 0x96, 0x77,
	0x42, 0xe1, 0x41, 0xca, 0x71, 0x7e, 0x96, 0x44, 0x27, 0x1a, 0x81, 0xa3, 0xfd, 0x4a, 0x32, 0xd2,
	0x85, 0xa6, 0xb9, 0x5f, 0xaa, 0xa7, 0xab, 0xda, 0xa4, 0x28, 0x52, 0xaf, 0x64, 0x2f, 0x2a, 0x84,
	0x13, 0xa9, 0xd9, 0x70, 0x58, 0x49, 0x46, 0x9e, 0x83, 0x87, 0x19, 0xd0, 0x4e, 0xad, 0xeb, 0x2c,
	0xd9, 0x54, 0xa4, 0xb0, 0x5c, 0x43, 0xbf, 0x82, 0x76, 0x29, 0x27, 0x86, 0xf2, 0xde, 0x94, 0x3a,
	0xe0, 0x89, 0xac, 0x46, 0x74, 0x46, 0x75, 0x96, 0x5f, 0xe9, 0x8f, 0x36, 0x3c, 0x64, 0xf8, 0xcd,
	0x2d, 0x0a, 0xf9, 0x3a, 0x91, 0xb8, 0x91, 0x94, 0x2e, 0x34, 0x03, 0x3f, 0x0e, 0x27, 0xa1, 0x2f,
	0x71, 0xc9, 0x4b, 0x51, 0xa4, 0x93, 0xf2, 0x85, 0x5c, 0xa7, 0xa6, 0x28, 0x23, 0x7b, 0x00, 0x53,
	0x5f, 0x94, 0x99, 0x29, 0x48, 0xe8, 0x2b, 0x68, 0x15, 0xc0, 0x6c, 0xca, 0xa6, 0x0b, 0xcd, 0x79,
	0x22, 0xf1, 0x98, 0xfb, 0xb1, 0xc4, 0xd0, 0x64, 0x54, 0x14, 0xd1, 0x08, 0xb6, 0x06, 0xd3, 0x09,
	0xc6, 0xd2, 0xbc, 0x46, 0x76, 0xd7, 0xcb, 0xbf, 0x51, 0x2c, 0xfb, 0x5d, 0x68, 0xc8, 0xc9, 0x0c,
	0x85, 0xf4, 0x67, 0xa9, 0x29, 0xaa, 0x95, 0x40, 0xd5, 0x43, 0xa0, 0x1f, 0x3b, 0x79, 0xa9, 0x93,
	0x6a, 0xb0, 0xe5, 0x9d, 0xfe, 0x6e, 0x43, 0x2b, 0x8f, 0x24, 0xd2, 0x24, 0x16, 0xa8, 0x46, 0xc1,
	0x7c, 0x82, 0xdf, 0x9e, 0x84, 0x06, 0xb3, 0xb9, 0xbd, 0x7d, 0x10, 0xc5, 0x41, 0x9c, 0x84, 0xa8,
	0xf9, 0x6a, 0x30, 0x7d, 0x26, 0xfb, 0x00, 0xea, 0x7f, 0x36, 0x5c, 0x8a, 0xed, 0x94, 0x49, 0x58,
	0x41, 0x4b, 0x7f, 0xb3, 0x61, 0xeb, 0x82, 0xe3, 0x05, 0xc7, 0xd4, 0xe7, 0xf8, 0xb5, 0x88, 0x36,
	0x62, 0xdc, 0x03, 0x10, 0x8a, 0xb1, 0x38, 0xc8, 0x3f, 0xb2, 0xc3, 0x0a, 0x12, 0xe5, 0x17, 0x4e,
	0x22, 0x14, 0xd2, 0x60, 0x34, 0x37, 0xf2, 0x11, 0x78, 0x3c, 0x63, 0xda, 0xb4, 0xfe, 0xb6, 0xee,
	0xbf, 0xe2, 0x27, 0x60, 0xb9, 0xc5, 0x32, 0x1d, 0x77, 0x95, 0x0e, 0x4d, 0x01, 0xfe, 0x45, 0x78,
	0xf7, 0x10, 0x48, 0x13, 0x68, 0x64, 0x9d, 0xf6, 0x5f, 0x05, 0xfc, 0xd9, 0x86, 0xfa, 0x59, 0x12,
	0x65, 0x63, 0xed, 0x63, 0xf0, 0x52, 0x8e, 0xea, 0xcf, 0x2c, 0x03, 0x4d, 0x58, 0xe9, 0x23, 0x8d,
	0x2c, 0x96, 0xdb, 0x90, 0x17, 0x50, 0xd5, 0xb6, 0xd9, 0x60, 0x6e, 0x19, 0xdb, 0x95, 0xa1, 0xd6,
	0x92, 0x0f, 0xa0, 0x16, 0x64, 0x03, 0x25, 0x1b, 0x82, 0x5b, 0xf9, 0x10, 0xd4, 0x49, 0x8e, 0x2c,
	0x66, 0xd4, 0x47, 0x1e, 0xb8, 0x6a, 0x82, 0x2c, 0xe8, 0xaf, 0x36, 0x3c, 0xbc, 0xb8, 0xba, 0x56,
	0xea, 0x7e, 0x10, 0x60, 0x2a, 0x31, 0x7c, 0x6b, 0x2e, 0x0a, 0x33, 0xc6, 0x29, 0xcd, 0x18, 0xf2,
	0x3e, 0xb4, 0xe4, 0x22, 0xc5, 0xf3, 0xeb, 0x3c, 0x86, 0xe1, 0x65, 0x4d, 0x7a, 0x5f, 0x61, 0xec,
	0xef, 0x43, 0xe5, 0x3c, 0x25, 0x1e, 0x38, 0xc7, 0xc3, 0xcb, 0xb6, 0xa5, 0x0e, 0xe3, 0xe1, 0x65,
	0xdb, 0x26, 0x0d, 0x70, 0x07, 0x67, 0xc3, 0x3e, 0x6b, 0x57, 0x94, 0x6c, 0xd0, 0x1f, 0xb7, 0x9d,
	0xde, 0x4f, 0x36, 0x78, 0xa7, 0xf3, 0xb1, 0x4c, 0x38, 0x92, 0x5d, 0x70, 0x8e, 0x51, 0x92, 0x7c,
	0x87, 0xed, 0x14, 0x7a, 0x83, 0x5a, 0xe4, 0x19, 0x38, 0x63, 0x94, 0xa4, 0xb4, 0xc4, 0xd6, 0x4c,
	0xba, 0xe0, 0x0e, 0xf4, 0xc6, 0x5a, 0x6d, 0xb1, 0x35, 0x8b, 0xa7, 0x3a, 0x2e, 0x29, 0x2c, 0xb1,
	0xb2, 0x41, 0xef, 0x17, 0x1b, 0x9a, 0x06, 0xcf, 0xc5, 0xd1, 0xab, 0x4b, 0xb5, 0xfb, 0x36, 0x63,
	0x3a, 0xb4, 0xc9, 0xf3, 0x37, 0xa2, 0x3a, 0xb4, 0x09, 0x7d, 0x13, 0xae, 0x43, 0x5b, 0xa5, 0xf7,
	0x8f, 0xc8, 0x0e, 0xed, 0xde, 0x0f, 0x36, 0x54, 0x99, 0x7f, 0x2d, 0xc9, 0x97, 0xb0, 0x55, 0x5a,
	0x21, 0xe4, 0xff, 0xca, 0xf2, 0xce, 0xa6, 0xdc, 0x79, 0x74, 0x47, 0xcc, 0x50, 0xb1, 0xf0, 0x19,
	0x34, 0x0b, 0x23, 0x9b, 0xfc, 0x2f, 0x8b, 0x53, 0x5a, 0x28, 0x3b, 0x64, 0x4d, 0xa8, 0x3d, 0x7b,
	0x7f, 0xd9, 0x50, 0x55, 0xc5, 0x47, 0xbe, 0x80, 0xed, 0xd2, 0xa8, 0xd0, 0x64, 0xdd, 0x9d, 0x20,
	0xd9, 0x33, 0xe5, 0x69, 0x4b, 0x2d, 0xf2, 0x39, 0xb4, 0x56, 0x7d, 0xb3, 0x72, 0x2d, 0xf5, 0xd2,
	0x8e, 0x86, 0xb5, 0x56, 0xe9, 0xd4, 0x22, 0x9f, 0x42, 0xb3, 0xe8, 0xb8, 0xd6, 0x58, 0x9b, 0xbc,
	0x7a, 0x00, 0x59, 0x57, 0x69, 0xa7, 0x72, 0x97, 0x6d, 0xf0, 0xb9, 0xaa, 0xe9, 0xdf, 0xc6, 0x9f,
	0xfc, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x40, 0xa7, 0xc5, 0x18, 0x27, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KvStoreClient is the client API for KvStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KvStoreClient interface {
	// Get the value associated with a key.
	Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Result, error)
	Set(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Result, error)
	Clear(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Result, error)
	CAS(ctx context.Context, in *CASArg, opts ...grpc.CallOption) (*Result, error)
}

type kvStoreClient struct {
	cc *grpc.ClientConn
}

func NewKvStoreClient(cc *grpc.ClientConn) KvStoreClient {
	return &kvStoreClient{cc}
}

func (c *kvStoreClient) Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/pb.KvStore/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvStoreClient) Set(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/pb.KvStore/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvStoreClient) Clear(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/pb.KvStore/Clear", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvStoreClient) CAS(ctx context.Context, in *CASArg, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/pb.KvStore/CAS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KvStoreServer is the server API for KvStore service.
type KvStoreServer interface {
	// Get the value associated with a key.
	Get(context.Context, *Key) (*Result, error)
	Set(context.Context, *KeyValue) (*Result, error)
	Clear(context.Context, *Empty) (*Result, error)
	CAS(context.Context, *CASArg) (*Result, error)
}

func RegisterKvStoreServer(s *grpc.Server, srv KvStoreServer) {
	s.RegisterService(&_KvStore_serviceDesc, srv)
}

func _KvStore_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvStoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KvStore/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvStoreServer).Get(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _KvStore_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvStoreServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KvStore/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvStoreServer).Set(ctx, req.(*KeyValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _KvStore_Clear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvStoreServer).Clear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KvStore/Clear",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvStoreServer).Clear(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KvStore_CAS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CASArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvStoreServer).CAS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KvStore/CAS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvStoreServer).CAS(ctx, req.(*CASArg))
	}
	return interceptor(ctx, in, info, handler)
}

var _KvStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.KvStore",
	HandlerType: (*KvStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _KvStore_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _KvStore_Set_Handler,
		},
		{
			MethodName: "Clear",
			Handler:    _KvStore_Clear_Handler,
		},
		{
			MethodName: "CAS",
			Handler:    _KvStore_CAS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kv.proto",
}

// KvStorePBFTClient is the client API for KvStorePBFT service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KvStorePBFTClient interface {
	// Get the value associated with a key.
	Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (KvStorePBFT_GetClient, error)
	Set(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (KvStorePBFT_SetClient, error)
	Clear(ctx context.Context, in *Empty, opts ...grpc.CallOption) (KvStorePBFT_ClearClient, error)
	CAS(ctx context.Context, in *CASArg, opts ...grpc.CallOption) (KvStorePBFT_CASClient, error)
}

type kvStorePBFTClient struct {
	cc *grpc.ClientConn
}

func NewKvStorePBFTClient(cc *grpc.ClientConn) KvStorePBFTClient {
	return &kvStorePBFTClient{cc}
}

func (c *kvStorePBFTClient) Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (KvStorePBFT_GetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_KvStorePBFT_serviceDesc.Streams[0], "/pb.KvStorePBFT/Get", opts...)
	if err != nil {
		return nil, err
	}
	x := &kvStorePBFTGetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KvStorePBFT_GetClient interface {
	Recv() (*Result, error)
	grpc.ClientStream
}

type kvStorePBFTGetClient struct {
	grpc.ClientStream
}

func (x *kvStorePBFTGetClient) Recv() (*Result, error) {
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *kvStorePBFTClient) Set(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (KvStorePBFT_SetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_KvStorePBFT_serviceDesc.Streams[1], "/pb.KvStorePBFT/Set", opts...)
	if err != nil {
		return nil, err
	}
	x := &kvStorePBFTSetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KvStorePBFT_SetClient interface {
	Recv() (*Result, error)
	grpc.ClientStream
}

type kvStorePBFTSetClient struct {
	grpc.ClientStream
}

func (x *kvStorePBFTSetClient) Recv() (*Result, error) {
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *kvStorePBFTClient) Clear(ctx context.Context, in *Empty, opts ...grpc.CallOption) (KvStorePBFT_ClearClient, error) {
	stream, err := c.cc.NewStream(ctx, &_KvStorePBFT_serviceDesc.Streams[2], "/pb.KvStorePBFT/Clear", opts...)
	if err != nil {
		return nil, err
	}
	x := &kvStorePBFTClearClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KvStorePBFT_ClearClient interface {
	Recv() (*Result, error)
	grpc.ClientStream
}

type kvStorePBFTClearClient struct {
	grpc.ClientStream
}

func (x *kvStorePBFTClearClient) Recv() (*Result, error) {
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *kvStorePBFTClient) CAS(ctx context.Context, in *CASArg, opts ...grpc.CallOption) (KvStorePBFT_CASClient, error) {
	stream, err := c.cc.NewStream(ctx, &_KvStorePBFT_serviceDesc.Streams[3], "/pb.KvStorePBFT/CAS", opts...)
	if err != nil {
		return nil, err
	}
	x := &kvStorePBFTCASClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KvStorePBFT_CASClient interface {
	Recv() (*Result, error)
	grpc.ClientStream
}

type kvStorePBFTCASClient struct {
	grpc.ClientStream
}

func (x *kvStorePBFTCASClient) Recv() (*Result, error) {
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KvStorePBFTServer is the server API for KvStorePBFT service.
type KvStorePBFTServer interface {
	// Get the value associated with a key.
	Get(*Key, KvStorePBFT_GetServer) error
	Set(*KeyValue, KvStorePBFT_SetServer) error
	Clear(*Empty, KvStorePBFT_ClearServer) error
	CAS(*CASArg, KvStorePBFT_CASServer) error
}

func RegisterKvStorePBFTServer(s *grpc.Server, srv KvStorePBFTServer) {
	s.RegisterService(&_KvStorePBFT_serviceDesc, srv)
}

func _KvStorePBFT_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Key)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KvStorePBFTServer).Get(m, &kvStorePBFTGetServer{stream})
}

type KvStorePBFT_GetServer interface {
	Send(*Result) error
	grpc.ServerStream
}

type kvStorePBFTGetServer struct {
	grpc.ServerStream
}

func (x *kvStorePBFTGetServer) Send(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

func _KvStorePBFT_Set_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(KeyValue)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KvStorePBFTServer).Set(m, &kvStorePBFTSetServer{stream})
}

type KvStorePBFT_SetServer interface {
	Send(*Result) error
	grpc.ServerStream
}

type kvStorePBFTSetServer struct {
	grpc.ServerStream
}

func (x *kvStorePBFTSetServer) Send(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

func _KvStorePBFT_Clear_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KvStorePBFTServer).Clear(m, &kvStorePBFTClearServer{stream})
}

type KvStorePBFT_ClearServer interface {
	Send(*Result) error
	grpc.ServerStream
}

type kvStorePBFTClearServer struct {
	grpc.ServerStream
}

func (x *kvStorePBFTClearServer) Send(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

func _KvStorePBFT_CAS_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CASArg)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KvStorePBFTServer).CAS(m, &kvStorePBFTCASServer{stream})
}

type KvStorePBFT_CASServer interface {
	Send(*Result) error
	grpc.ServerStream
}

type kvStorePBFTCASServer struct {
	grpc.ServerStream
}

func (x *kvStorePBFTCASServer) Send(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

var _KvStorePBFT_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.KvStorePBFT",
	HandlerType: (*KvStorePBFTServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Get",
			Handler:       _KvStorePBFT_Get_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Set",
			Handler:       _KvStorePBFT_Set_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Clear",
			Handler:       _KvStorePBFT_Clear_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CAS",
			Handler:       _KvStorePBFT_CAS_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kv.proto",
}

// RaftClient is the client API for Raft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RaftClient interface {
	AppendEntries(ctx context.Context, in *AppendEntriesArgs, opts ...grpc.CallOption) (*AppendEntriesRet, error)
	RequestVote(ctx context.Context, in *RequestVoteArgs, opts ...grpc.CallOption) (*RequestVoteRet, error)
}

type raftClient struct {
	cc *grpc.ClientConn
}

func NewRaftClient(cc *grpc.ClientConn) RaftClient {
	return &raftClient{cc}
}

func (c *raftClient) AppendEntries(ctx context.Context, in *AppendEntriesArgs, opts ...grpc.CallOption) (*AppendEntriesRet, error) {
	out := new(AppendEntriesRet)
	err := c.cc.Invoke(ctx, "/pb.Raft/AppendEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) RequestVote(ctx context.Context, in *RequestVoteArgs, opts ...grpc.CallOption) (*RequestVoteRet, error) {
	out := new(RequestVoteRet)
	err := c.cc.Invoke(ctx, "/pb.Raft/RequestVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftServer is the server API for Raft service.
type RaftServer interface {
	AppendEntries(context.Context, *AppendEntriesArgs) (*AppendEntriesRet, error)
	RequestVote(context.Context, *RequestVoteArgs) (*RequestVoteRet, error)
}

func RegisterRaftServer(s *grpc.Server, srv RaftServer) {
	s.RegisterService(&_Raft_serviceDesc, srv)
}

func _Raft_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Raft/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).AppendEntries(ctx, req.(*AppendEntriesArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Raft/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).RequestVote(ctx, req.(*RequestVoteArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _Raft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Raft",
	HandlerType: (*RaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntries",
			Handler:    _Raft_AppendEntries_Handler,
		},
		{
			MethodName: "RequestVote",
			Handler:    _Raft_RequestVote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kv.proto",
}

// PbftClient is the client API for Pbft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PbftClient interface {
	ClientRequestPBFT(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientResponse, error)
	PrePreparePBFT(ctx context.Context, in *PrePrepareMsg, opts ...grpc.CallOption) (*PbftMsgAccepted, error)
	PreparePBFT(ctx context.Context, in *PrepareMsg, opts ...grpc.CallOption) (*PbftMsgAccepted, error)
	CommitPBFT(ctx context.Context, in *CommitMsg, opts ...grpc.CallOption) (*PbftMsgAccepted, error)
}

type pbftClient struct {
	cc *grpc.ClientConn
}

func NewPbftClient(cc *grpc.ClientConn) PbftClient {
	return &pbftClient{cc}
}

func (c *pbftClient) ClientRequestPBFT(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientResponse, error) {
	out := new(ClientResponse)
	err := c.cc.Invoke(ctx, "/pb.Pbft/ClientRequestPBFT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) PrePreparePBFT(ctx context.Context, in *PrePrepareMsg, opts ...grpc.CallOption) (*PbftMsgAccepted, error) {
	out := new(PbftMsgAccepted)
	err := c.cc.Invoke(ctx, "/pb.Pbft/PrePreparePBFT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) PreparePBFT(ctx context.Context, in *PrepareMsg, opts ...grpc.CallOption) (*PbftMsgAccepted, error) {
	out := new(PbftMsgAccepted)
	err := c.cc.Invoke(ctx, "/pb.Pbft/PreparePBFT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) CommitPBFT(ctx context.Context, in *CommitMsg, opts ...grpc.CallOption) (*PbftMsgAccepted, error) {
	out := new(PbftMsgAccepted)
	err := c.cc.Invoke(ctx, "/pb.Pbft/CommitPBFT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PbftServer is the server API for Pbft service.
type PbftServer interface {
	ClientRequestPBFT(context.Context, *ClientRequest) (*ClientResponse, error)
	PrePreparePBFT(context.Context, *PrePrepareMsg) (*PbftMsgAccepted, error)
	PreparePBFT(context.Context, *PrepareMsg) (*PbftMsgAccepted, error)
	CommitPBFT(context.Context, *CommitMsg) (*PbftMsgAccepted, error)
}

func RegisterPbftServer(s *grpc.Server, srv PbftServer) {
	s.RegisterService(&_Pbft_serviceDesc, srv)
}

func _Pbft_ClientRequestPBFT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).ClientRequestPBFT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Pbft/ClientRequestPBFT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).ClientRequestPBFT(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_PrePreparePBFT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrePrepareMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).PrePreparePBFT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Pbft/PrePreparePBFT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).PrePreparePBFT(ctx, req.(*PrePrepareMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_PreparePBFT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).PreparePBFT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Pbft/PreparePBFT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).PreparePBFT(ctx, req.(*PrepareMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_CommitPBFT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).CommitPBFT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Pbft/CommitPBFT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).CommitPBFT(ctx, req.(*CommitMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pbft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Pbft",
	HandlerType: (*PbftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClientRequestPBFT",
			Handler:    _Pbft_ClientRequestPBFT_Handler,
		},
		{
			MethodName: "PrePreparePBFT",
			Handler:    _Pbft_PrePreparePBFT_Handler,
		},
		{
			MethodName: "PreparePBFT",
			Handler:    _Pbft_PreparePBFT_Handler,
		},
		{
			MethodName: "CommitPBFT",
			Handler:    _Pbft_CommitPBFT_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kv.proto",
}
